root: ./src/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  domain-registry-essentials/general-overview: domain-registry-essentials/architecture-overview.md
  domain-registry-essentials/reference: domain-registry-essentials/records-reference.md
